import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from '../providers/reactQueryProvider'
import { NextProvider } from '@/providers/nextUiProvider'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Lista de afazeres',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <ReactQueryProvider> 
        <body className={`${inter.className} min-h-screen`}>
          <NextProvider>
            {children}
          </NextProvider>
        </body>
      </ReactQueryProvider>
    </html>
  )
}
